sed -i "s/from .vue/from \"vue/"  	./resources/js/shared/NavBar.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Layouts/AppLayout.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Items/Create.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Archives/IndexEx.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Archives/RequestEx.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Archives/ArchivesTable.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Archives/Index.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Archives/Request.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/SalesBuzz/EditItemMap.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/SalesBuzz/IndexItemsMap.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/SalesBuzz/IndexBranchesMap.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Mobis/EditItemMap.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Mobis/IndexItemsMap.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Mobis/IndexBranchesMap.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Setup/Step2.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Setup/Step1.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Setup/Step3.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/POS/Add.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/POS/Index.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Reports/BranchesSales.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Reports/Summary.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Reports/Purchase.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Reports/CustomersSales.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Application/Settings.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Users/Edit.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Users/Index.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Auth/Login.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Auth/Register.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Accounting/Chart/Edit.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Accounting/Chart/Upload.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Accounting/Chart/Index.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Receipts/Index.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Invoices/Search.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Invoices/Preview.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Invoices/IndexReceived.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Invoices/EditLine.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Invoices/UpdateReceived.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Invoices/Add.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Invoices/UploadIndex.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Invoices/CreditNote.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Invoices/DebitNote.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Invoices/Index.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Customers/Edit.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Customers/Index.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Branches/Edit.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Branches/Index.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Dashboard/StatisticsTable.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Dashboard/index.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Pages/Dashboard/charts.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/models/ComponentsFilter.js
sed -i "s/from .vue/from \"vue/"  	./resources/js/Charts/TopItemsByStatus.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Charts/TopReceivers.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Charts/TopItems.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Charts/TopReceiversByStatus.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Jetstream/Modal.vue
sed -i "s/from .vue/from \"vue/"  	./resources/js/Jetstream/Dropdown.vue
