<?php

namespace App\Models\ETA;

/**
 * Eloquent class to describe the ETAInvoices table.
 *
 * automatically generated by ModelGenerator.php
 */
class ETAInvoice extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'ETAInvoices';

    public $primaryKey = 'Id';

    public $timestamps = false;

    protected $fillable = ['uuid', 'submissionUUID', 'longId', 'internalId', 'typeName', 'typeVersionName', 'issuerId',
        'issuerName', 'receiverId', 'receiverName', 'dateTimeIssued', 'dateTimeReceived', 'totalSales', 'totalDiscount',
        'netAmount', 'total', 'cancelRequestDate', 'rejectRequestDate', 'cancelRequestDelayedDate', 'rejectRequestDelayedDate',
        'declineCancelRequestDate', 'declineRejectRequestDate', 'status', 'createdByUserId', 'receiver_id', 'reviewer', 'comment', 'document'];

    public function getDates()
    {
        return ['dateTimeIssued', 'dateTimeReceived', 'cancelRequestDate', 'rejectRequestDate', 'cancelRequestDelayedDate', 'rejectRequestDelayedDate', 'declineCancelRequestDate', 'declineRejectRequestDate'];
    }
    
    public function branch()
    {
        return $this->belongsTo('App\Models\ETA\Issuer', 'receiver_id', 'Id');
    }
}
