<?php

namespace App\Models\ETA;

/**
 * Eloquent class to describe the Item table.
 *
 * automatically generated by ModelGenerator.php
 */
class Item extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'Item';

    public $primaryKey = 'Id';

    protected $fillable = ['codeType', 'parentCode', 'itemCode', 'codeName', 'codeNameAr', 'activeFrom', 'activeTo',
        'description', 'descriptionAr', 'requestReason'];

    public function getDates()
    {
        return ['activeFrom', 'activeTo'];
    }
}
