<?php

namespace App\Models\ETA;

/**
 * Eloquent class to describe the Payment table.
 *
 * automatically generated by ModelGenerator.php
 */
class Payment extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'Payment';

    public $primaryKey = 'Id';

    protected $fillable = ['bankName', 'bankAddress', 'bankAccountNo', 'bankAccountIBAN', 'swiftCode', 'terms'];

    public function invoice()
    {
        return $this->hasMany('App\Models\ETA\Invoice', 'payment_id', 'Id');
    }
}
