<?php

namespace App\Models\ETA;

use Illuminate\Support\Facades\DB;

//use App\Models\Item;

/**
 * Eloquent class to describe the InvoiceLine table.
 *
 * automatically generated by ModelGenerator.php
 */
class ReceiptItem extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'rc_receiptItem';

    public $primaryKey = 'id';

    protected $casts = [
        'id'        => 'integer',
        'quantity'  => 'float', 
        'unitPrice' => 'float', 
        'netSale'   => 'float', 
        'totalSale' => 'float', 
        'total'     => 'float'
    ];

    protected $fillable = ['receipt_id', 'internalCode', 'description', 'itemType', 'itemCode', 'unitType',
        'quantity', 'unitPrice', 'netSale', 'totalSale','total'];

    public function item()
    {
        return $this->belongsTo('App\Models\ETA\ETAItem', 'itemCode', 'itemCode');
    }

    public function receipt()
    {
        return $this->belongsTo('App\Models\ETA\Receipt', 'receipt_id', 'id');
    }

    public function taxableItems()
    {
        return $this->hasMany('App\Models\ETA\ReceiptTaxableItem', 'receiptItem_id', 'id');
    }
}
