<?php

namespace App\Models\ETA;

/**
 * Eloquent class to describe the TaxTotal table.
 *
 * automatically generated by ModelGenerator.php
 */
class ReceiptTaxTotal extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'rc_taxTotal';

    public $primaryKey = 'Id';
    protected $casts = [
        'Id'      => 'integer',
        'amount'  => 'float', 
    ];

    protected $fillable = ['taxType', 'amount', 'receipt_id'];

    public function receipt()
    {
        return $this->belongsTo('App\Models\ETA\Receipt', 'receipt_id', 'Id');
    }
}
