<?php

namespace App\Models\ETA;

use Illuminate\Support\Facades\DB;

/**
 * Eloquent class to describe the Receiver table.
 *
 * automatically generated by ModelGenerator.php
 */
class Receiver extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'Receiver';

    public $primaryKey = 'Id';

    protected $fillable = ['type', 'receiver_id', 'name', 'code'];

    public function address()
    {
        return $this->belongsTo('App\Models\ETA\Address', 'address_id', 'Id');
    }

    public function invoice()
    {
        return $this->hasMany('App\Models\ETA\Invoice', 'receiver_id', 'Id');
    }

    public function getTopReceiversStats($hasFilter = false)
    {
        $query = $this->select(DB::raw('Receiver.name as name, sum(Invoice.netAmount) as value'))
            ->join('Invoice', 'Invoice.receiver_id', '=', 'Receiver.id');

        if ($hasFilter) {
            $query->whereIn('Invoice.status', request('statusList'));
        }

        return $query->groupBy('name')
            ->orderBY('value', 'DESC')
            ->limit(10)
            ->get();
    }
}
