<?php

namespace App\Models\ETA;

/**
 * Eloquent class to describe the TaxTotal table.
 *
 * automatically generated by ModelGenerator.php
 */
class TaxTotal extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'TaxTotal';

    public $primaryKey = 'Id';

    protected $fillable = ['taxType', 'amount', 'invoice_id'];

    public function invoice()
    {
        return $this->belongsTo('App\Models\ETA\Invoice', 'invoice_id', 'Id');
    }
}
