<?php

namespace App;

/**
 * Eloquent class to describe the teams table.
 *
 * automatically generated by ModelGenerator.php
 */
class Teams extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'teams';

    protected $fillable = ['user_id', 'name', 'personal_team'];

    public function teamInvitations()
    {
        return $this->hasMany('App\TeamInvitations', 'team_id', 'id');
    }
}
