<?php

namespace App;

/**
 * Eloquent class to describe the team_user table.
 *
 * automatically generated by ModelGenerator.php
 */
class TeamUser extends \Illuminate\Database\Eloquent\Model
{
    protected $table = 'team_user';

    protected $fillable = ['team_id', 'user_id', 'role'];
}
